"""
csv-to-tnea.py — convert TNEA cutoff CSV(s) into Vazhi data files.

Usage:
  python3 tools/csv-to-tnea.py tools/tnea-cutoffs.csv

Generates data/tnea-meta.js and data/tnea.js

Expected CSV columns:
  year, college, college_short, college_type, district,
  branch, community, quota, cutoff_mark

Communities: OC, BC, BCM, MBC, SC, SCA, ST (TN standard 7).
Subcategories MBCDNC and MBCV fold into MBC.
Quotas: General, 7.5GS (Govt-school 7.5%), NRI, Sports.

Cutoffs stored as integers (mark × 100) to keep decimal precision.
Row format: [year, inst_idx, branch_idx, quota_code, comm_code, cutoff_x100]
"""

import csv, json, os, sys

COMM_MAP = {
    'OC': 0, 'BC': 1, 'BCM': 2, 'MBC': 3, 'SC': 4, 'SCA': 5, 'ST': 6,
    'MBCDNC': 3, 'MBCV': 3,
}
QUOTA_MAP = {
    'General': 0, 'GEN': 0,
    '7.5GS': 1, '7.5%GS': 1, '7.5 GS': 1,
    'NRI': 2,
    'Sports': 3,
}
TYPE_NORMALISE = {
    'Government': 'Government', 'Govt': 'Government', 'Govt.': 'Government',
    'Aided': 'Aided', 'Govt Aided': 'Aided', 'Government Aided': 'Aided',
    'Self-financing': 'Self-financing', 'Self Financing': 'Self-financing',
    'SF': 'Self-financing', 'Private': 'Self-financing',
}

colleges, college_shorts, college_types, college_districts = [], [], [], []
branches = []
college_idx_map, branch_idx_map = {}, {}
rows = []
skipped = 0

script_dir = os.path.dirname(os.path.abspath(__file__))
root_dir   = os.path.dirname(script_dir)

if len(sys.argv) < 2:
    sys.exit("Usage: python3 tools/csv-to-tnea.py <path/to/file.csv>")

for path in sys.argv[1:]:
    with open(path, encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        reader.fieldnames = [h.strip() for h in (reader.fieldnames or [])]
        for r in reader:
            r = {k.strip(): v.strip() for k, v in r.items()}

            try:
                year = int(r.get('year', ''))
                mark = float(r.get('cutoff_mark', ''))
            except ValueError:
                skipped += 1
                continue

            college  = r.get('college', '').strip()
            short    = r.get('college_short', '').strip() or college
            ctype    = TYPE_NORMALISE.get(r.get('college_type', '').strip(), 'Self-financing')
            district = r.get('district', '').strip()
            branch   = r.get('branch', '').strip()
            comm_raw = r.get('community', '').strip()
            quota_raw= r.get('quota', 'General').strip() or 'General'

            if not (college and branch and comm_raw):
                skipped += 1
                continue

            comm_code  = COMM_MAP.get(comm_raw)
            quota_code = QUOTA_MAP.get(quota_raw, 0)
            if comm_code is None:
                skipped += 1
                continue

            if college not in college_idx_map:
                college_idx_map[college] = len(colleges)
                colleges.append(college)
                college_shorts.append(short)
                college_types.append(ctype)
                college_districts.append(district)

            if branch not in branch_idx_map:
                branch_idx_map[branch] = len(branches)
                branches.append(branch)

            rows.append([
                year,
                college_idx_map[college],
                branch_idx_map[branch],
                quota_code,
                comm_code,
                int(round(mark * 100)),
            ])

if not rows:
    sys.exit("No rows loaded — check CSV format.")

meta_path = os.path.join(root_dir, 'data', 'tnea-meta.js')
meta_content = (
    "// Auto-generated by tools/csv-to-tnea.py — do not hand-edit\n"
    "// Scope note: this file may include self-financing colleges (a deliberate\n"
    "// exception to CLAUDE.md §27's strict scope rule). The exception applies\n"
    "// only to the TNEA predictor dataset — the Colleges tab (colleges-tn.js)\n"
    "// remains govt + aided only.\n"
    "const TNEA_META = {\n"
    f"  colleges:        {json.dumps(colleges, ensure_ascii=False)},\n"
    f"  collegeShort:    {json.dumps(college_shorts, ensure_ascii=False)},\n"
    f"  collegeType:     {json.dumps(college_types, ensure_ascii=False)},\n"
    f"  collegeDistrict: {json.dumps(college_districts, ensure_ascii=False)},\n"
    f"  branches:        {json.dumps(branches, ensure_ascii=False)},\n"
    '  communities:     ["OC","BC","BCM","MBC","SC","SCA","ST"],\n'
    '  quotas:          ["General","TN 7.5% Govt-school","NRI","Sports"]\n'
    "};\n"
)
with open(meta_path, 'w', encoding='utf-8') as f:
    f.write(meta_content)

data_path = os.path.join(root_dir, 'data', 'tnea.js')
data_content = (
    "// Auto-generated by tools/csv-to-tnea.py — do not hand-edit\n"
    "// Row format: [year, collegeIdx, branchIdx, quotaCode, commCode, cutoff_x100]\n"
    "const TNEA_ROWS = " + json.dumps(rows) + ";\n"
)
with open(data_path, 'w', encoding='utf-8') as f:
    f.write(data_content)

print("Done!")
print(f"  Colleges : {len(colleges)}")
print(f"  Branches : {len(branches)}")
print(f"  Rows     : {len(rows)}")
print(f"  Skipped  : {skipped}")
print(f"  Written  : {meta_path}")
print(f"           : {data_path}")
