"""
csv-to-josaa.py — One-time script to convert JoSAA allotment CSV(s) into Vazhi data files.

Usage (single combined file):
  python3 tools/csv-to-josaa.py tools/josaa-2020-2025-all-rounds-with-state.csv

Usage (multiple per-year files):
  python3 tools/csv-to-josaa.py          # auto-detects josaa_*.csv in tools/

The script generates data/josaa-meta.js and data/josaa.js
Only Round 6 rows are kept (final round = most predictive for future applicants).

Expected CSV columns:
  Year, Round, Institute Type, Exam, Institute, State,
  Academic Program Name, Quota, Seat Type, Gender, Opening Rank, Closing Rank
"""

import csv, json, glob, os, sys

QUOTA_MAP = {
    'HS': 0, 'OS': 1, 'AI': 2, 'GO': 3,
    'Home State': 0, 'Other State': 1, 'All India': 2,
}
SEAT_MAP = {
    'OPEN': 0, 'EWS': 1, 'OBC-NCL': 2, 'SC': 3, 'ST': 4,
    'OPEN (PwD)': 5, 'EWS (PwD)': 6, 'OBC-NCL (PwD)': 7,
    'SC (PwD)': 8, 'ST (PwD)': 9,
}
GENDER_MAP = {
    'Gender-Neutral': 0,
    'Female-only (including Supernumerary)': 1,
    'Female-only': 1,
}

institutes, programs, inst_types, inst_states = [], [], [], []
inst_idx_map, prog_idx_map = {}, {}
rows = []
skipped = 0

script_dir = os.path.dirname(os.path.abspath(__file__))
root_dir   = os.path.dirname(script_dir)

# Accept explicit file paths as arguments, or fall back to josaa_*.csv glob
if len(sys.argv) > 1:
    csv_files = sys.argv[1:]
else:
    pattern   = os.path.join(script_dir, 'josaa_*.csv')
    csv_files = sorted(glob.glob(pattern))

if not csv_files:
    sys.exit(
        "No CSV file found.\n"
        "Usage: python3 tools/csv-to-josaa.py <path/to/file.csv>\n"
        "Or place josaa_*.csv files in the tools/ folder and run without arguments."
    )

print(f"Found {len(csv_files)} CSV file(s): {[os.path.basename(f) for f in csv_files]}")

for path in csv_files:
    file_rows = 0
    with open(path, encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        # Normalise column names (strip whitespace)
        reader.fieldnames = [h.strip() for h in (reader.fieldnames or [])]
        for r in reader:
            r = {k.strip(): v.strip() for k, v in r.items()}

            # Keep Round 6 only
            round_val = (r.get('round') or r.get('Round') or r.get('Round Number') or '').strip()
            if round_val != '6':
                continue

            inst  = (r.get('institute') or r.get('Institute') or r.get('Institute Name') or '').strip()
            prog  = (r.get('program') or r.get('Academic Program Name') or r.get('Program Name') or '').strip()
            state = (r.get('state') or r.get('State') or '').strip()
            itype = (r.get('instituteType') or r.get('Institute Type') or '').strip()
            year_str = (r.get('year') or r.get('Year') or '').strip()

            if not (inst and prog and year_str):
                skipped += 1
                continue

            try:
                year = int(year_str)
                open_rank  = int(r.get('openingRank') or r.get('Opening Rank') or 0)
                close_rank = int(r.get('closingRank') or r.get('Closing Rank') or 0)
            except ValueError:
                skipped += 1
                continue

            if inst not in inst_idx_map:
                inst_idx_map[inst] = len(institutes)
                institutes.append(inst)
                inst_types.append(itype)
                inst_states.append(state)

            if prog not in prog_idx_map:
                prog_idx_map[prog] = len(programs)
                programs.append(prog)

            quota_raw  = (r.get('quota') or r.get('Quota') or 'AI').strip()
            seat_raw   = (r.get('seatType') or r.get('Seat Type') or 'OPEN').strip()
            gender_raw = (r.get('gender') or r.get('Gender') or 'Gender-Neutral').strip()

            quota_code  = QUOTA_MAP.get(quota_raw, 2)
            seat_code   = SEAT_MAP.get(seat_raw, 0)
            gender_code = GENDER_MAP.get(gender_raw, 0)

            rows.append([
                year,
                inst_idx_map[inst],
                prog_idx_map[prog],
                quota_code,
                seat_code,
                gender_code,
                open_rank,
                close_rank,
            ])
            file_rows += 1

    print(f"  {os.path.basename(path)}: {file_rows} Round-6 rows loaded")

if not rows:
    sys.exit("No Round 6 rows found. Check that your CSVs have a 'Round' column with value '6'.")

# ── Write josaa-meta.js ──────────────────────────────────────────────
meta_path = os.path.join(root_dir, 'data', 'josaa-meta.js')
meta_content = f"""// Auto-generated by tools/csv-to-josaa.py — do not hand-edit
const JOSAA_META = {{
  institutes: {json.dumps(institutes, ensure_ascii=False)},
  programs:   {json.dumps(programs,   ensure_ascii=False)},
  instType:   {json.dumps(inst_types, ensure_ascii=False)},
  instState:  {json.dumps(inst_states,ensure_ascii=False)},
  quota:      ["HS","OS","AI","GO"],
  seatType:   ["OPEN","EWS","OBC-NCL","SC","ST","OPEN (PwD)","EWS (PwD)","OBC-NCL (PwD)","SC (PwD)","ST (PwD)"],
  gender:     ["Gender-Neutral","Female-only"]
}};
"""
with open(meta_path, 'w', encoding='utf-8') as f:
    f.write(meta_content)

# ── Write josaa.js ───────────────────────────────────────────────────
data_path = os.path.join(root_dir, 'data', 'josaa.js')
data_content = "// Auto-generated by tools/csv-to-josaa.py — do not hand-edit\nconst JOSAA_ROWS = " + json.dumps(rows) + ";\n"
with open(data_path, 'w', encoding='utf-8') as f:
    f.write(data_content)

print(f"\nDone!")
print(f"  Institutes : {len(institutes)}")
print(f"  Programs   : {len(programs)}")
print(f"  Rows       : {len(rows)}")
print(f"  Skipped    : {skipped}")
print(f"  Written    : {meta_path}")
print(f"             : {data_path}")
